version: '3.9'

services:
  db:
    container_name: personalized_gifts_db
    image: postgres:latest
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      SSLMODE: "disable"
    ports:
      - "${DB_PORT}:5432"
    networks:
      - backend

  app:
    container_name: personalized_gifts_app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${GO_PORT}:4000"
    volumes:
      - ./cmd/api:/app
    depends_on:
      - db
    networks:
      - backend

networks:
  backend:
    driver: bridge
